name: Add Rewards

on:
  workflow_dispatch:
    inputs:
      period_seconds:
        description: 'Lock period in seconds (e.g., 604800 for 7 days)'
        required: true
        type: string
        default: '604800'
      reward_amount:
        description: 'Reward amount in smallest unit (e.g., 10000000 for 10 tokens)'
        required: true
        type: string
        default: '10000000'
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - testnet
          - mainnet
        default: 'testnet'

jobs:
  add-rewards:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
        
    - name: Install Stellar CLI
      run: |
        curl -sSL https://github.com/stellar/stellar-cli/releases/latest/download/stellar-cli-23.1.3-x86_64-unknown-linux-gnu.tar.gz | tar -xz -C /usr/local/bin

    - name: Build contract
      run: |
        cd contracts/vaquita-pool
        make build
        
    - name: Add rewards
      run: |
        cd contracts/vaquita-pool
        if [ "${{ github.event.inputs.environment }}" = "mainnet" ]; then
          export SOURCE_ACCOUNT="${{ secrets.STELLAR_PRIVATE_KEY_MAINNET }}"
          export USER_ADDRESS="${{ secrets.USER_ADDRESS_MAINNET }}"
          export CONTRACT_ID="${{ secrets.CONTRACT_ID_MAINNET }}"
        else
          export SOURCE_ACCOUNT="${{ secrets.STELLAR_PRIVATE_KEY_TESTNET }}"
          export USER_ADDRESS="${{ secrets.USER_ADDRESS_TESTNET }}"
          export CONTRACT_ID="${{ secrets.CONTRACT_ID_TESTNET }}"
        fi
        export PERIOD="${{ github.event.inputs.period_seconds }}"
        export REWARD_AMOUNT="${{ github.event.inputs.reward_amount }}"
        export NETWORK="${{ github.event.inputs.environment }}"
        
        # Add rewards using Stellar CLI
        stellar contract invoke \
          --source $SOURCE_ACCOUNT \
          --network $NETWORK \
          --id $CONTRACT_ID \
          -- \
          add_rewards \
          --caller $USER_ADDRESS \
          --period $PERIOD \
          --reward_amount $REWARD_AMOUNT

